# Generated by Django 4.2.1 on 2023-05-23 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.IntegerField(choices=[(1, 'Reporte Estrategico 01'), (2, 'Reporte Estrategico 02'), (3, 'Reporte Tactico 01'), (4, 'Reporte Tactico 02'), (5, 'Reporte Tactico 03')])),
                ('fecha_hora_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiltroReporte',
            fields=[
                ('id_filtro_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField(blank=True, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencial.reporte')),
            ],
        ),
    ]
